### ISSUE TITLE
error when updating content type

### ISSUE THREAD

**Issue by msuhovec** [contentful/contentful-management.py#17] opened 2017-06-27 14:57 UTC
Consider this simple program:

from contentful_management import Client

client = Client('XXXXXXXXXXXXXXXXXXXXX')
space_id = 'yyyyyyyyyy'
content_type_id = 'collectionCallRanges'

content_type = client.content_types(space_id).find(content_type_id)

print content_type.name

content_type.name = "Something Else"
content_type.save()

Gives an error

 python update_collectionCallRanges2.py
CollectionCallRanges
Traceback (most recent call last):
  File "update_collectionCallRanges2.py", line 12, in <module>
    content_type.save()
  File "/Users/msuhovec/python_envs/wse_usurper/lib/python2.7/site-packages/contentful_management/resource.py", line 109, in save
    return self.update()
  File "/Users/msuhovec/python_envs/wse_usurper/lib/python2.7/site-packages/contentful_management/resource.py", line 99, in update
    headers=headers
  File "/Users/msuhovec/python_envs/wse_usurper/lib/python2.7/site-packages/contentful_management/client.py", line 538, in _put
    return self._request('put', url, attributes, **kwargs)
  File "/Users/msuhovec/python_envs/wse_usurper/lib/python2.7/site-packages/contentful_management/client.py", line 506, in _request
    raise error
contentful_management.errors.BadRequestError: You need to omit a field before deleting it

I am on version 1.3.1

**Comment by dlitvakb** [comment] 2017-06-27 15:35
Hey @msuhovec,

Looks like fields are not getting included somehow.

I'm currently implementing all new endpoints that have been added lately, I will squeeze a fix for this as well if I find what's going on.

Cheers

**Comment by dlitvakb** [comment] 2017-07-03 15:03
Managed to reproduce, looking for a solution.

**Comment by dlitvakb** [comment] 2017-07-03 15:07
Found the issue, field ID's were being snake cased when they shouldn't have been.

Fixing.

**Closed** 2017-07-06 14:14 UTC
Labels: bug

**Comment by dlitvakb** [comment] 2017-07-06 14:16
Version 1.3.2 with the fix for this has been released.

Cheers

**Comment by msuhovec** [comment] 2017-07-06 14:18
Thanks, Dave!
